name: Docker Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-app:latest .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ec2-dev-flask:latest
          docker stop ec2-dev-app || true && docker rm ec2-dev-app || true
          docker run -d --name ec2-dev-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/ec2-dev-flask:latest
